language: node_js
script: npm test
node_js:
- node
- io.js
- '0.12'
notifications:
  email:
  - eng+build+verifyengine@wealthfront.com
deploy:
  provider: npm
  email: ops+npm@wealthfront.com
  api_key:
    secure: BXXIkLO7My36ZAKgD25ZrAAj53cezy7Dy+Dk5PpZzYokQtmXPlQILWGEYvV9eR/lIIjEG0fjvPmoyGUTT5bJuNjbT+BiUkqwm6j8wBv8+d3pyl9gneurx26+aqnGZCYdayRxQzwnMf9FdwC+D3NepOu5GNGYdjvDIu2QXdy4rHpi29x72DPYiHdskA95u1nTxKYraxhUAbjjkgnGTjctR/nkMZenn4zGY/I+ScPUtkSOLEinNRR+VquEPdzPjS1oiB/Eq1ZyDfQeDkzO4G4DK2k4FZZPNg9p0YBz+cpl1dS6Zy7TkII91NOsT5LrtgEXl4I0MOmtFO6OH73vlL/tC6mURjT2CzghDGh4DUK9RjNH4hT5WxsQnVQYFi+vwsqVmnUPyQ+suiUYjod7FnRQGDhhNkCn2E8araB7aQm4ipluE3lDBu6jI1Xny1mwBwKsOXnfpRVw65lbMnoLcFE2m+Jo8513m0G0wpatga3eYfrbe+dC5mAepGF9hKDlQOwYuYgKnILLjtBENIYtB4harY2IrZnfeWl0GTx8DsSCkkNlBCBgLYJ8i1E1HRHOQsp3C7nG5WLT75Ym/+sz/C/ENSD/kTiNH/x8mg7Yx5WrMnVmHJr4JcDwnMk0bnKoLOxqclIem5Lz1W0++qeV8wLvRD1RbpZ1UD6U3QyiRZ/93/U=
  on:
    tags: true
    repo: wealthfront/verify-engine
    node: '0.12'
